services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports (local)
      - "${LOCAL_IP}:53:53/tcp"
      - "${LOCAL_IP}:53:53/udp"
      # DNS Ports (external)
      - "${MESH_IP}:53:53/tcp"
      - "${MESH_IP}:53:53/udp"
      # HTTP Ports - managed by Caddy
    environment:
      TZ: "Europe/Warsaw"
      FTLCONF_webserver_api_password: ${API_PASSWORD}
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - "./etc-pihole:/etc/pihole"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MESH_IP=${MESH_IP}
      - LOCAL_IP=${LOCAL_IP}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
